### PR TITLE
Theiler window for boxed correlation

### LINKED ISSUE #159: q-order correlationsum is unintuitive
The q-order correlationsum currently follows the definition given by [Kantz and Schreiber](https://doi.org/10.1017/CBO9780511755798):
Screenshot from 2021-02-02 11-53-05
with
Screenshot from 2021-02-02 11-53-24
or in the  case of the boxed correlationsum:
Screenshot from 2021-02-02 11-52-45

 This leads to the requirement of multiplication by a factor of `1/(q-1)` after the linear regression has been made. Taking the definition given by [Grassberger on scholarpedia](http://www.scholarpedia.org/w/index.php?title=Grassberger-Procaccia_algorithm&action=cite&rev=91330):
Screenshot from 2021-02-02 11-56-30

and applying all other corrections, would solve this issue and make the q-order correlationsum more accessible.

### PR DESCRIPTION
**Pull request by apbraun**
I'll finish up the tests and this should be good to go.

Closes #159

### CODE REVIEW

**Comment by apbraun** [comment]
The tests just compare the `boxed_correlationsum` to the classic `correlationsum` which is already assured to be equal to one when the whole domain is considered.

**Comment by apbraun** [comment]
The tests are failing on orbitdiagrams. It says that `Systems` is not defined.

**Comment by Datseris** [comment]
Sorry about that, was my fault. Should be valid tests now. Can you update the mathematical formulas accordingly as in #159 ?

**Comment by Datseris** [comment]
Tests do not pass locally for me.

**Comment by apbraun** [comment]
Yeah that's my bad. Apparently there is no boxing and hence no need for a box size in the classic correlation sum :grin:. 
I included the exponent to satisfy #159. Also ran some benchmarks on the version with the Theiler window and compared it to the original one. I'm a bit confused that the version without Theiler window seems to be slightly slower (~3%) than the version with it, even when the window is not applied.

**Comment by Datseris** [comment]
I'll give it a quick test with our project before merging and post figures here. Will have to wait a bit, i'm a bit busy with other projects at the moment.

**Comment by Datseris** [comment]
image

Looks okay to me

File: src/dimensions/correlationdim.jl [hunk 1]
```diff
@@ -215,30 +221,33 @@ See also: [`correlation_boxing`](@ref),
...
+function boxed_correlationsum(data, εs, r0 = maximum(εs); q = 2, M = size(data, 2), w = 0)
     @assert M ≤ size(data, 2) "Prism dimension has to be lower or equal than " *
     "data dimension."
     boxes, contents = correlation_boxing(data, r0, M)
     if q == 2
-        boxed_correlationsum_2(boxes, contents, data, εs)
+        boxed_correlationsum_2(boxes, contents, data, εs, w = w)
     else
-        boxed_correlationsum_q(boxes, contents, data, εs, q)
+        boxed_correlationsum_q(boxes, contents, data, εs, q, w = w)
```
Comment (Datseris) [inline src/dimensions/correlationdim.jl:250]: KEyword arguments should always be separated by positional arguments with `;` instead of `,`

File: src/dimensions/correlationdim.jl [hunk 2]
```diff
@@ -317,44 +328,60 @@ function find_neighborboxes_2(index, boxes, contents)
...
+                # Calculate distance.
+		        dist = evaluate(norm, data[index_Y], x)
+		        for k in Nε:-1:1
+		            if dist < εs[k]
+		                Cs[k] += 1
+		            else
+		                break
+		            end
+		        end
+		    end
```
Comment (Datseris) [inline src/dimensions/correlationdim.jl:362]: there seems to be an identation missmatch here.

**Review by Datseris — APPROVED** [review]
Okay this is good to go, only minor comments. You also need to add a changelog entry and increment minor version value.
